"""empty message

Revision ID: 569f4e09b231
Revises: 9bc688822e2b
Create Date: 2020-11-10 11:34:28.737002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569f4e09b231'
down_revision = '9bc688822e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
